# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 688)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setGeometry(QtCore.QRect(0, 0, 151, 661))
        self.icon_only_widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(118, 171, 174);\n"
"}\n"
"\n"
"QPushButton {\n"
"  min-width: 70px;\n"
"  height: 40px;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  font-weight: bold;\n"
"  cursor: pointer;\n"
"  transition: all 0.3s ease;\n"
"  position: relative;\n"
"  display: inline-block;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  border: 2px solid #adb5bd;\n"
"  background: #adb5bd;\n"
"}\n"
"QPushButton:hover {\n"
"  background: #fff;\n"
"  color: #adb5bd\n"
"}\n"
"\n"
"QLineEdit {\n"
"\n"
"}\n"
"")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.add_script = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.add_script.setGeometry(QtCore.QRect(20, 630, 111, 24))
        self.add_script.setObjectName("add_script")
        self.label_script = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label_script.setGeometry(QtCore.QRect(30, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        font.setBold(True)
        self.label_script.setFont(font)
        self.label_script.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_script.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_script.setObjectName("label_script")
        self.text_script_add = QtWidgets.QLineEdit(parent=self.icon_only_widget)
        self.text_script_add.setGeometry(QtCore.QRect(10, 600, 131, 22))
        self.text_script_add.setObjectName("text_script_add")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 0, 811, 661))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(49, 54, 63);\n"
"}\n"
"\n"
"QTextEdit {\n"
"    \n"
"    border-color: rgb(118, 171, 174);\n"
"}")
        self.widget.setObjectName("widget")
        self.widget_cmd = QtWidgets.QWidget(parent=self.widget)
        self.widget_cmd.setGeometry(QtCore.QRect(10, 430, 791, 221))
        self.widget_cmd.setObjectName("widget_cmd")
        self.cmd = QtWidgets.QTextEdit(parent=self.widget_cmd)
        self.cmd.setGeometry(QtCore.QRect(10, 10, 771, 201))
        self.cmd.setReadOnly(True)
        self.cmd.setObjectName("cmd")
        self.widget_view = QtWidgets.QWidget(parent=self.widget)
        self.widget_view.setGeometry(QtCore.QRect(19, 19, 771, 401))
        self.widget_view.setObjectName("widget_view")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.widget_view)
        self.graphicsView.setGeometry(QtCore.QRect(5, 1, 761, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.icon_only_widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget_2.setGeometry(QtCore.QRect(960, 0, 151, 661))
        self.icon_only_widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(118, 171, 174);\n"
"}\n"
"\n"
"QPushButton {\n"
"  min-width: 70px;\n"
"  height: 40px;\n"
"  color: #fff;\n"
"  padding: 5px 10px;\n"
"  font-weight: bold;\n"
"  cursor: pointer;\n"
"  transition: all 0.3s ease;\n"
"  position: relative;\n"
"  display: inline-block;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  border: 2px solid #adb5bd;\n"
"  background: #adb5bd;\n"
"}\n"
"QPushButton:hover {\n"
"  background: #fff;\n"
"  color: #adb5bd\n"
"}\n"
"")
        self.icon_only_widget_2.setObjectName("icon_only_widget_2")
        self.add_variable = QtWidgets.QPushButton(parent=self.icon_only_widget_2)
        self.add_variable.setGeometry(QtCore.QRect(20, 630, 111, 24))
        self.add_variable.setObjectName("add_variable")
        self.label_variable = QtWidgets.QLabel(parent=self.icon_only_widget_2)
        self.label_variable.setGeometry(QtCore.QRect(40, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        font.setBold(True)
        self.label_variable.setFont(font)
        self.label_variable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_variable.setObjectName("label_variable")
        self.text_variable_add = QtWidgets.QLineEdit(parent=self.icon_only_widget_2)
        self.text_variable_add.setGeometry(QtCore.QRect(10, 600, 131, 22))
        self.text_variable_add.setObjectName("text_variable_add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1112, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuBlock = QtWidgets.QMenu(parent=self.menuBar)
        self.menuBlock.setObjectName("menuBlock")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport = QtGui.QAction(parent=MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(parent=MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSearch = QtGui.QAction(parent=MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuBlock.addAction(self.actionSearch)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuBlock.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_script.setText(_translate("MainWindow", "Add"))
        self.label_script.setText(_translate("MainWindow", "Scripts"))
        self.add_variable.setText(_translate("MainWindow", "Add"))
        self.label_variable.setText(_translate("MainWindow", "Variable"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuBlock.setTitle(_translate("MainWindow", "Block"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
